name: Actualizar sitemap

on:
  push:
    paths:
      - entradas.json
      - scripts/generar_sitemap.py

jobs:
  generar:
    runs-on: ubuntu-latest

    steps:
      - name: Clonar repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.x

      - name: Ejecutar script Python
        run: python scripts/generar_sitemap.py

      - name: Subir cambios a sitemap.xml
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add sitemap.xml
          git commit -m "🔄 Actualización automática del sitemap" || echo "Sin cambios"
          git push